repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        exclude: ^Charts/.*/templates
      - id: check-merge-conflict
      - id: end-of-file-fixer
