name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit

  container:
    needs: helm
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      # publish is always true as there is no tests for dev-c7 at present
      publish: true
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml

  helm:
    uses: ./.github/workflows/_helm.yml
    permissions:
      contents: read
      packages: write

  release:
    needs: [container, docs, helm, lint]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
