name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,type-checking

  container:
    needs: helm
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      publish: ${{ needs.test.result == 'success' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml

  helm:
    uses: ./.github/workflows/_helm.yml
    permissions:
      contents: read
      packages: write

  release:
    needs: [container, docs, helm]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
